version: '3.8'

networks:
  inredd:
    name: inredd
    driver: bridge

services:
  inredd-web-api:
    image: inredd-web-api
    container_name: inredd-web-api
    build:
      context: ./inredd-web-api
      dockerfile: docker/Dockerfile
    networks:
      - inredd
    restart: always
    ports:
      - "8881:8881"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_TIMEOUT: 30
    volumes:
      - ./inredd-web-api:/app
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3" # entrypoint: ["tail", "-f", "/dev/null"]
